name: "42Crunch REST API Static Security Testing"

# Run workflow each time code is pushed to your repository
on: [push]

jobs:
  test-apis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 42Crunch REST API Static Security Testing
      uses: 42Crunch/api-security-audit-action@v1
      with:
        # Please create free account at https://platform.42crunch.com/register
        # Follow these steps to configure API_TOKEN https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
        api-token: ${{ secrets.API_TOKEN }}
        # Fail if any OpenAPI file scores lower than 75
        min-score: 75
        # Upload results to Github code scanning
        upload-to-code-scanning: true
